#!/bin/sh

guess_version () {
	agvtool what-marketing-version -terse1
}

build () {
	xcodebuild clean DSTROOT="$1" ${XCODEBUILD_OPTS}
	xcodebuild install DSTROOT="$1" ${XCODEBUILD_OPTS}
	
	# clean up temporary build products
	cd "$1"
	rm -rf tmp
}

. $(dirname $0)/mowgli
