#!/bin/sh

contents() {
    grep '^[^#]' < .toybox/TOC
}

install() {
    mkdir -p "/$(dirname "$1")" &&
      ln -snf "$(pwd)/contents/$1" "/$1"
}

install_contents() {
    contents | while read c; do
        install "$c" || return 1
    done
}

install_contents

if [ $? -ne 0 ]; then
    echo "couldn't install package"
    exit 6
fi
