#!/bin/sh

contents() {
    grep '^[^#]' < .toybox/TOC
}

uninstall() {
    rm -rf "/$1"
}

uninstall_contents() {
    contents | while read c; do
        uninstall "$c" || return 1
    done
}

uninstall_contents

if [ $? -ne 0 ]; then
    echo "couldn't uninstall package"
    exit 7
fi
